"""initial_tables

Revision ID: a3206323f0db
Revises: b01260bc56af
Create Date: 2026-02-13 11:20:07.292814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3206323f0db'
down_revision = 'b01260bc56af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限代码（如：user:create, procurement:approve）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块（如：user, procurement, supplier）'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=True)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_index(op.f('ix_permission_is_deleted'), 'permission', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_permission_module'), 'permission', ['module'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称（如：admin, manager, employee）'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统内置角色'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_is_deleted'), 'role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('supplier',
    sa.Column('name', sa.String(length=200), nullable=False, comment='供应商名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='供应商编码'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='供应商类型（general:普通, strategic:战略, key:关键）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态（active:活跃, inactive:不活跃, suspended:暂停, blacklisted:黑名单）'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='联系人'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('contact_email', sa.String(length=255), nullable=True, comment='联系邮箱'),
    sa.Column('contact_address', sa.Text(), nullable=True, comment='联系地址'),
    sa.Column('company_name', sa.String(length=200), nullable=True, comment='公司名称'),
    sa.Column('registration_number', sa.String(length=100), nullable=True, comment='工商注册号'),
    sa.Column('tax_number', sa.String(length=100), nullable=True, comment='税务登记号'),
    sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'),
    sa.Column('registered_capital', sa.Float(), nullable=True, comment='注册资本（万元）'),
    sa.Column('established_date', sa.DateTime(), nullable=True, comment='成立日期'),
    sa.Column('qualification_level', sa.String(length=50), nullable=True, comment='资质等级'),
    sa.Column('qualification_certificates', sa.JSON(), nullable=True, comment='资质证书信息'),
    sa.Column('quality_system', sa.String(length=100), nullable=True, comment='质量体系认证'),
    sa.Column('industry_certifications', sa.JSON(), nullable=True, comment='行业认证'),
    sa.Column('overall_rating', sa.Float(), nullable=False, comment='综合评分（0-5）'),
    sa.Column('quality_rating', sa.Float(), nullable=False, comment='质量评分'),
    sa.Column('delivery_rating', sa.Float(), nullable=False, comment='交付评分'),
    sa.Column('service_rating', sa.Float(), nullable=False, comment='服务评分'),
    sa.Column('price_rating', sa.Float(), nullable=False, comment='价格评分'),
    sa.Column('assessment_date', sa.DateTime(), nullable=True, comment='最近评估日期'),
    sa.Column('cooperation_start_date', sa.DateTime(), nullable=True, comment='合作开始日期'),
    sa.Column('total_transaction_amount', sa.Float(), nullable=False, comment='累计交易金额'),
    sa.Column('total_transaction_count', sa.Integer(), nullable=False, comment='累计交易次数'),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=True, comment='最后交易日期'),
    sa.Column('bank_name', sa.String(length=100), nullable=True, comment='开户银行'),
    sa.Column('bank_account', sa.String(length=100), nullable=True, comment='银行账号'),
    sa.Column('account_name', sa.String(length=100), nullable=True, comment='账户名称'),
    sa.Column('credit_limit', sa.Float(), nullable=True, comment='信用额度'),
    sa.Column('payment_terms', sa.String(length=100), nullable=True, comment='付款条件'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件信息'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=True)
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_is_deleted'), 'supplier', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=False)
    op.create_index(op.f('ix_supplier_status'), 'supplier', ['status'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='邮箱是否验证'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录IP'),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='员工工号'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='所属部门'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('hire_date', sa.DateTime(), nullable=True, comment='入职日期'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_employee_id'), 'user', ['employee_id'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('procurement_request',
    sa.Column('request_number', sa.String(length=50), nullable=False, comment='需求编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='需求标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='需求描述'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='申请部门'),
    sa.Column('purpose', sa.Text(), nullable=True, comment='用途说明'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级（urgent:紧急, high:高, normal:正常, low:低）'),
    sa.Column('required_date', sa.DateTime(), nullable=True, comment='要求到货日期'),
    sa.Column('budget_amount', sa.Float(), nullable=True, comment='预算金额'),
    sa.Column('budget_code', sa.String(length=100), nullable=True, comment='预算编码'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', name='procurementstatus'), nullable=False, comment='需求状态'),
    sa.Column('submission_date', sa.DateTime(), nullable=True, comment='提交日期'),
    sa.Column('approval_date', sa.DateTime(), nullable=True, comment='审批日期'),
    sa.Column('approver_id', sa.UUID(), nullable=True, comment='审批人ID'),
    sa.Column('approval_notes', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('approval_flow', sa.JSON(), nullable=True, comment='审批流程记录'),
    sa.Column('requester_id', sa.UUID(), nullable=False, comment='申请人ID'),
    sa.Column('related_project', sa.String(length=200), nullable=True, comment='关联项目'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_request_id'), 'procurement_request', ['id'], unique=False)
    op.create_index(op.f('ix_procurement_request_is_deleted'), 'procurement_request', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_procurement_request_request_number'), 'procurement_request', ['request_number'], unique=True)
    op.create_index(op.f('ix_procurement_request_requester_id'), 'procurement_request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_procurement_request_status'), 'procurement_request', ['status'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='角色权限关联表'
    )
    op.create_table('supplier_evaluation',
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='供应商ID'),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False, comment='评估日期'),
    sa.Column('evaluator_id', sa.UUID(), nullable=False, comment='评估人ID'),
    sa.Column('evaluation_type', sa.String(length=50), nullable=False, comment='评估类型（periodic:定期, transaction:交易后, spot:抽查）'),
    sa.Column('quality_score', sa.Float(), nullable=False, comment='质量评分（0-5）'),
    sa.Column('delivery_score', sa.Float(), nullable=False, comment='交付评分（0-5）'),
    sa.Column('service_score', sa.Float(), nullable=False, comment='服务评分（0-5）'),
    sa.Column('price_score', sa.Float(), nullable=False, comment='价格评分（0-5）'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='综合评分'),
    sa.Column('strengths', sa.Text(), nullable=True, comment='优势'),
    sa.Column('weaknesses', sa.Text(), nullable=True, comment='不足'),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True, comment='改进建议'),
    sa.Column('evaluation_result', sa.String(length=50), nullable=False, comment='评估结果（excellent:优秀, good:良好, qualified:合格, poor:不合格）'),
    sa.Column('follow_up_actions', sa.Text(), nullable=True, comment='跟进措施'),
    sa.Column('next_evaluation_date', sa.DateTime(), nullable=True, comment='下次评估日期'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='评估附件'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_evaluation_id'), 'supplier_evaluation', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluation_is_deleted'), 'supplier_evaluation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_supplier_evaluation_supplier_id'), 'supplier_evaluation', ['supplier_id'], unique=False)
    op.create_table('supplier_product',
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='供应商ID'),
    sa.Column('product_name', sa.String(length=200), nullable=False, comment='产品名称'),
    sa.Column('product_code', sa.String(length=100), nullable=False, comment='产品编码'),
    sa.Column('product_category', sa.String(length=100), nullable=True, comment='产品类别'),
    sa.Column('product_specification', sa.Text(), nullable=True, comment='产品规格'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='计量单位'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='货币'),
    sa.Column('min_order_quantity', sa.Integer(), nullable=True, comment='最小起订量'),
    sa.Column('delivery_lead_time', sa.Integer(), nullable=True, comment='交货周期（天）'),
    sa.Column('quality_standard', sa.String(length=200), nullable=True, comment='质量标准'),
    sa.Column('certification', sa.JSON(), nullable=True, comment='产品认证'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_product_id'), 'supplier_product', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_product_is_deleted'), 'supplier_product', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_supplier_product_product_code'), 'supplier_product', ['product_code'], unique=False)
    op.create_index(op.f('ix_supplier_product_supplier_id'), 'supplier_product', ['supplier_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='用户角色关联表'
    )
    op.create_table('purchase_order',
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='订单编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='订单标题'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ISSUED', 'CONFIRMED', 'PARTIALLY_DELIVERED', 'DELIVERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'INVOICED', 'PAID', 'CLOSED', 'CANCELLED', name='orderstatus'), nullable=False, comment='订单状态'),
    sa.Column('procurement_request_id', sa.UUID(), nullable=True, comment='采购需求ID'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='供应商ID'),
    sa.Column('contract_number', sa.String(length=100), nullable=True, comment='合同编号'),
    sa.Column('contract_date', sa.DateTime(), nullable=True, comment='合同日期'),
    sa.Column('contract_amount', sa.Float(), nullable=False, comment='合同金额'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币'),
    sa.Column('payment_terms', sa.Text(), nullable=True, comment='付款条件'),
    sa.Column('delivery_terms', sa.Text(), nullable=True, comment='交货条件'),
    sa.Column('warranty_terms', sa.Text(), nullable=True, comment='质保条款'),
    sa.Column('order_date', sa.DateTime(), nullable=False, comment='订单日期'),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True, comment='预计交货日期'),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True, comment='实际交货日期'),
    sa.Column('completion_date', sa.DateTime(), nullable=True, comment='完成日期'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='税率'),
    sa.Column('tax_amount', sa.Float(), nullable=False, comment='税额'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='总金额'),
    sa.Column('advance_payment_amount', sa.Float(), nullable=False, comment='预付款金额'),
    sa.Column('advance_payment_percentage', sa.Float(), nullable=False, comment='预付款比例'),
    sa.Column('approver_id', sa.UUID(), nullable=True, comment='审批人ID'),
    sa.Column('approval_date', sa.DateTime(), nullable=True, comment='审批日期'),
    sa.Column('approval_notes', sa.Text(), nullable=True, comment='审批意见'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['procurement_request_id'], ['procurement_request.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_id'), 'purchase_order', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_is_deleted'), 'purchase_order', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_purchase_order_order_number'), 'purchase_order', ['order_number'], unique=True)
    op.create_index(op.f('ix_purchase_order_procurement_request_id'), 'purchase_order', ['procurement_request_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_status'), 'purchase_order', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_order_supplier_id'), 'purchase_order', ['supplier_id'], unique=False)
    op.create_table('request_item',
    sa.Column('request_id', sa.UUID(), nullable=False, comment='需求ID'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='物品名称'),
    sa.Column('item_code', sa.String(length=100), nullable=True, comment='物品编码'),
    sa.Column('specification', sa.Text(), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='数量'),
    sa.Column('estimated_unit_price', sa.Float(), nullable=True, comment='预估单价'),
    sa.Column('estimated_total_price', sa.Float(), nullable=True, comment='预估总价'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='品牌'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='生产厂家'),
    sa.Column('required_date', sa.DateTime(), nullable=True, comment='要求到货日期'),
    sa.Column('usage_location', sa.String(length=200), nullable=True, comment='使用地点'),
    sa.Column('technical_requirements', sa.Text(), nullable=True, comment='技术要求'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_item_id'), 'request_item', ['id'], unique=False)
    op.create_index(op.f('ix_request_item_is_deleted'), 'request_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_request_item_request_id'), 'request_item', ['request_id'], unique=False)
    op.create_table('delivery_note',
    sa.Column('delivery_number', sa.String(length=50), nullable=False, comment='送货单号'),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', 'RECEIVED', 'CANCELLED', name='deliverystatus'), nullable=False, comment='送货状态'),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False, comment='采购订单ID'),
    sa.Column('supplier_id', sa.UUID(), nullable=False, comment='供应商ID'),
    sa.Column('logistics_company', sa.String(length=100), nullable=True, comment='物流公司'),
    sa.Column('tracking_number', sa.String(length=100), nullable=True, comment='运单号'),
    sa.Column('delivery_date', sa.DateTime(), nullable=True, comment='发货日期'),
    sa.Column('expected_arrival_date', sa.DateTime(), nullable=True, comment='预计到达日期'),
    sa.Column('actual_arrival_date', sa.DateTime(), nullable=True, comment='实际到达日期'),
    sa.Column('receiver_id', sa.UUID(), nullable=True, comment='收货人ID'),
    sa.Column('receipt_date', sa.DateTime(), nullable=True, comment='收货日期'),
    sa.Column('receipt_notes', sa.Text(), nullable=True, comment='收货备注'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_note_delivery_number'), 'delivery_note', ['delivery_number'], unique=True)
    op.create_index(op.f('ix_delivery_note_id'), 'delivery_note', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_note_is_deleted'), 'delivery_note', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_delivery_note_purchase_order_id'), 'delivery_note', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_delivery_note_status'), 'delivery_note', ['status'], unique=False)
    op.create_table('order_item',
    sa.Column('order_id', sa.UUID(), nullable=False, comment='订单ID'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='物品名称'),
    sa.Column('item_code', sa.String(length=100), nullable=True, comment='物品编码'),
    sa.Column('specification', sa.Text(), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('quantity', sa.Float(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='总价'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='品牌'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='生产厂家'),
    sa.Column('delivery_date', sa.DateTime(), nullable=True, comment='要求交货日期'),
    sa.Column('warranty_period', sa.String(length=100), nullable=True, comment='质保期'),
    sa.Column('technical_requirements', sa.Text(), nullable=True, comment='技术要求'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    op.create_index(op.f('ix_order_item_is_deleted'), 'order_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_table('delivery_item',
    sa.Column('delivery_note_id', sa.UUID(), nullable=False, comment='送货单ID'),
    sa.Column('order_item_id', sa.UUID(), nullable=True, comment='订单项ID'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='物品名称'),
    sa.Column('item_code', sa.String(length=100), nullable=True, comment='物品编码'),
    sa.Column('specification', sa.Text(), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('ordered_quantity', sa.Float(), nullable=False, comment='订购数量'),
    sa.Column('delivered_quantity', sa.Float(), nullable=False, comment='送货数量'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=True, comment='总价'),
    sa.Column('batch_number', sa.String(length=100), nullable=True, comment='批号'),
    sa.Column('production_date', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('expiry_date', sa.DateTime(), nullable=True, comment='有效期至'),
    sa.Column('quality_status', sa.String(length=50), nullable=True, comment='质量状态'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_item_delivery_note_id'), 'delivery_item', ['delivery_note_id'], unique=False)
    op.create_index(op.f('ix_delivery_item_id'), 'delivery_item', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_item_is_deleted'), 'delivery_item', ['is_deleted'], unique=False)
    op.create_table('inventory_receipt',
    sa.Column('receipt_number', sa.String(length=50), nullable=False, comment='入库单号'),
    sa.Column('status', sa.Enum('PENDING', 'INSPECTING', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', 'STORED', 'CANCELLED', name='receiptstatus'), nullable=False, comment='入库状态'),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False, comment='采购订单ID'),
    sa.Column('delivery_note_id', sa.UUID(), nullable=True, comment='送货单ID'),
    sa.Column('inspector_id', sa.UUID(), nullable=True, comment='验收人ID'),
    sa.Column('inspection_date', sa.DateTime(), nullable=True, comment='验收日期'),
    sa.Column('inspection_method', sa.String(length=100), nullable=True, comment='验收方式'),
    sa.Column('inspection_result', sa.Text(), nullable=True, comment='验收结果'),
    sa.Column('quality_rating', sa.String(length=50), nullable=True, comment='质量评级'),
    sa.Column('warehouse_location', sa.String(length=200), nullable=True, comment='仓库位置'),
    sa.Column('storage_condition', sa.String(length=100), nullable=True, comment='存储条件'),
    sa.Column('receipt_date', sa.DateTime(), nullable=True, comment='入库日期'),
    sa.Column('storekeeper_id', sa.UUID(), nullable=True, comment='仓管员ID'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_note.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['storekeeper_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_receipt_id'), 'inventory_receipt', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_receipt_is_deleted'), 'inventory_receipt', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_inventory_receipt_purchase_order_id'), 'inventory_receipt', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_inventory_receipt_receipt_number'), 'inventory_receipt', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_inventory_receipt_status'), 'inventory_receipt', ['status'], unique=False)
    op.create_table('receipt_item',
    sa.Column('receipt_id', sa.UUID(), nullable=False, comment='入库单ID'),
    sa.Column('delivery_item_id', sa.UUID(), nullable=True, comment='送货单项ID'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='物品名称'),
    sa.Column('item_code', sa.String(length=100), nullable=True, comment='物品编码'),
    sa.Column('specification', sa.Text(), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=50), nullable=True, comment='单位'),
    sa.Column('delivered_quantity', sa.Float(), nullable=False, comment='送货数量'),
    sa.Column('accepted_quantity', sa.Float(), nullable=False, comment='验收数量'),
    sa.Column('rejected_quantity', sa.Float(), nullable=False, comment='拒收数量'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='单价'),
    sa.Column('total_price', sa.Float(), nullable=True, comment='总价'),
    sa.Column('batch_number', sa.String(length=100), nullable=True, comment='批号'),
    sa.Column('production_date', sa.DateTime(), nullable=True, comment='生产日期'),
    sa.Column('expiry_date', sa.DateTime(), nullable=True, comment='有效期至'),
    sa.Column('storage_location', sa.String(length=200), nullable=True, comment='存储位置'),
    sa.Column('quality_status', sa.String(length=50), nullable=True, comment='质量状态'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='拒收原因'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['delivery_item.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['inventory_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_item_id'), 'receipt_item', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_item_is_deleted'), 'receipt_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_receipt_item_receipt_id'), 'receipt_item', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_item_receipt_id'), table_name='receipt_item')
    op.drop_index(op.f('ix_receipt_item_is_deleted'), table_name='receipt_item')
    op.drop_index(op.f('ix_receipt_item_id'), table_name='receipt_item')
    op.drop_table('receipt_item')
    op.drop_index(op.f('ix_inventory_receipt_status'), table_name='inventory_receipt')
    op.drop_index(op.f('ix_inventory_receipt_receipt_number'), table_name='inventory_receipt')
    op.drop_index(op.f('ix_inventory_receipt_purchase_order_id'), table_name='inventory_receipt')
    op.drop_index(op.f('ix_inventory_receipt_is_deleted'), table_name='inventory_receipt')
    op.drop_index(op.f('ix_inventory_receipt_id'), table_name='inventory_receipt')
    op.drop_table('inventory_receipt')
    op.drop_index(op.f('ix_delivery_item_is_deleted'), table_name='delivery_item')
    op.drop_index(op.f('ix_delivery_item_id'), table_name='delivery_item')
    op.drop_index(op.f('ix_delivery_item_delivery_note_id'), table_name='delivery_item')
    op.drop_table('delivery_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_is_deleted'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_delivery_note_status'), table_name='delivery_note')
    op.drop_index(op.f('ix_delivery_note_purchase_order_id'), table_name='delivery_note')
    op.drop_index(op.f('ix_delivery_note_is_deleted'), table_name='delivery_note')
    op.drop_index(op.f('ix_delivery_note_id'), table_name='delivery_note')
    op.drop_index(op.f('ix_delivery_note_delivery_number'), table_name='delivery_note')
    op.drop_table('delivery_note')
    op.drop_index(op.f('ix_request_item_request_id'), table_name='request_item')
    op.drop_index(op.f('ix_request_item_is_deleted'), table_name='request_item')
    op.drop_index(op.f('ix_request_item_id'), table_name='request_item')
    op.drop_table('request_item')
    op.drop_index(op.f('ix_purchase_order_supplier_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_status'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_procurement_request_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_order_number'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_is_deleted'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_supplier_product_supplier_id'), table_name='supplier_product')
    op.drop_index(op.f('ix_supplier_product_product_code'), table_name='supplier_product')
    op.drop_index(op.f('ix_supplier_product_is_deleted'), table_name='supplier_product')
    op.drop_index(op.f('ix_supplier_product_id'), table_name='supplier_product')
    op.drop_table('supplier_product')
    op.drop_index(op.f('ix_supplier_evaluation_supplier_id'), table_name='supplier_evaluation')
    op.drop_index(op.f('ix_supplier_evaluation_is_deleted'), table_name='supplier_evaluation')
    op.drop_index(op.f('ix_supplier_evaluation_id'), table_name='supplier_evaluation')
    op.drop_table('supplier_evaluation')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_procurement_request_status'), table_name='procurement_request')
    op.drop_index(op.f('ix_procurement_request_requester_id'), table_name='procurement_request')
    op.drop_index(op.f('ix_procurement_request_request_number'), table_name='procurement_request')
    op.drop_index(op.f('ix_procurement_request_is_deleted'), table_name='procurement_request')
    op.drop_index(op.f('ix_procurement_request_id'), table_name='procurement_request')
    op.drop_table('procurement_request')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_employee_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_supplier_status'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_is_deleted'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_is_deleted'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_module'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_deleted'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###